"""Pixel-exact helpers for building and exporting tilesets."""

from .core import (
    TilesetGrid,
    TilesetSlice,
    build_tileset_bundle,
    resize_tileset,
    resize_tileset_canvas,
    slice_tileset,
)
from .patterns import (
    DualGridTerrainProfile,
    TerrainPatternKind,
    TerrainPatternResult,
    TerrainPatternTile,
    build_fragment_terrain_pattern,
    build_manual_terrain_pattern,
    build_smart_terrain_pattern,
    build_terrain_pattern_bundle,
    build_tilesetter_terrain_pattern,
    dual_grid_terrain_profiles,
    generate_terrain_pattern,
    render_godot_terrain_installer,
    render_terrain_bitmask_template,
    terrain_pattern_layout,
    terrain_pattern_manifest,
    terrain_pattern_masks,
    terrain_pattern_set_layout,
)

__all__ = [
    "TilesetGrid",
    "TilesetSlice",
    "DualGridTerrainProfile",
    "TerrainPatternKind",
    "TerrainPatternResult",
    "TerrainPatternTile",
    "build_fragment_terrain_pattern",
    "build_manual_terrain_pattern",
    "build_tilesetter_terrain_pattern",
    "build_smart_terrain_pattern",
    "build_tileset_bundle",
    "build_terrain_pattern_bundle",
    "dual_grid_terrain_profiles",
    "generate_terrain_pattern",
    "render_godot_terrain_installer",
    "render_terrain_bitmask_template",
    "resize_tileset",
    "resize_tileset_canvas",
    "slice_tileset",
    "terrain_pattern_manifest",
    "terrain_pattern_layout",
    "terrain_pattern_masks",
    "terrain_pattern_set_layout",
]
